name: Feature request
about: Suggest an idea for cLog
labels: enhancement
body:
  - type: input
    attributes:
      label: What feature do you want?
      description: Be as specific as possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Why is this needed? What problem does it solve?
      validations:
        required: false
  - type: textarea
    attributes:
      label: Possible solution
      description: Optional: sketch or describe how this could work.
      validations:
        required: false
