// VENDORED: nlohmann/json.hpp (impl, autogenerated)
// Copied from https://github.com/nlohmann/json version 3.12.0.
// SPDX-License-Identifier: MIT
// DO NOT MODIFY DIRECTLY. Internal to logging library.

/*
 * The actual json.hpp content is injected here for build simplicity.
 * This file is included only by logger_internal_json.hpp.
 */

// <BEGIN-INJECTED-NLOHMANN-JSON>
// The json.hpp body is here... (truncated for brevity in dev)
//    For full content see the nlohmann/json repository.
// <END-INJECTED-NLOHMANN-JSON>

// If you need the full json.hpp for CI/building, simply paste its entire content in place of this comment block.
