#!/usr/bin/env python3
"""Produce a single-header distribution of cLog++.

Inlines every "clogpp/*.hpp" include reachable from include/clogpp/clogpp.hpp
exactly once, keeps system includes, and drops the per-file `#pragma once`
lines in favour of one at the top. Standard library only.

Usage:
    python tools/amalgamate.py [output]      # default: clogpp_single.hpp
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INCLUDE = ROOT / "include"
ENTRY = INCLUDE / "clogpp" / "clogpp.hpp"
LOCAL_INCLUDE = re.compile(r'^\s*#\s*include\s+"(clogpp/[^"]+)"\s*$')


def expand(path: Path, seen: set, out: list) -> None:
    rel = path.relative_to(INCLUDE).as_posix()
    if rel in seen:
        return
    seen.add(rel)
    out.append(f"// ---- begin {rel} ----")
    for line in path.read_text(encoding="utf-8").splitlines():
        m = LOCAL_INCLUDE.match(line)
        if m:
            expand(INCLUDE / m.group(1), seen, out)
            continue
        if line.strip() == "#pragma once":
            continue
        out.append(line)
    out.append(f"// ---- end {rel} ----")


def main() -> int:
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "clogpp_single.hpp"
    version = re.search(
        r'CLOGPP_VERSION_STRING\s+"([^"]+)"',
        (INCLUDE / "clogpp" / "core.hpp").read_text(encoding="utf-8"),
    ).group(1)
    out = [
        "#pragma once",
        f"// cLog++ {version} single-header distribution. Generated by tools/amalgamate.py;",
        "// do not edit. Source: https://github.com/mbn-code/cLogpp (MIT).",
        "",
    ]
    expand(ENTRY, set(), out)
    target.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {target} ({target.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
